### ISSUE TITLE
Custom path issues

### ISSUE THREAD

**Issue by mgrouch** [philseeley/boatinstrument#10]
How to convert K degrees to C degrees. 
In custom box there is scale parameter but
there is no way to do subtraction for units with different base. 

Another issue is that I can’t see values on any 
custom path box other than the first one. 

Only one box with custom SignalK path would show values. 

I’ve added navigation.magneticVariation and it works. 

When I add environment.outside.temperature 
or environment.outside.pressure 
they do not show. Even though they are in SignalK 

Might be there is ID collision? 

Thanks

**Comment by philseeley** [comment]
@mgrouch the custom box was really an attempt to get users to test a path and then submit their settings to get a proper box included. Mainly as I can't test paths properly for sources I don't have. Trying to cater for every possible conversion would have required parsing of formula etc, something I decided was overkill. Is there a specific temp path/Box you're trying to add?

I've tested multiple custom boxes with differs't paths and it all works OK for me. For the values that don't work for you, do the values fall outside the min/max setting? Or is the data very static and therefore have a timestamp greater than the "Data Timeout" value? What paths/Boxes are you looking to add?

**Comment by mgrouch** [comment]
I’ve tried adding 

navigation.magneticVariation
environment.outside.temperature
environment.outside.pressure

BTW 
More complete list of SignalK paths per spec 

https://github.com/bareboat-necessities/my-bareboat/blob/master/homeassistant/signalk-paths.txt

I’ll try to test more. 

Thanks

**Comment by philseeley** [comment]
That's a long list :o) probably won't get them all done.

If you do get paths to work OK and tune the Precision, Length etc, then if you press the Email button on the Settings page it "should" email me all the details. Although it probably only works on the platform the Flutter email package properly supports.

**Comment by philseeley** [comment]
Added Boxes for 'Magnetic Variation', 'Outside Temperature' and 'Outside Pressure' and bumped version number.
