### ISSUE TITLE
Radius for anchor alarm shouldn't go negative

### ISSUE THREAD

**Issue by mgrouch** [philseeley/boatinstrument#12]
Radius for anchor alarm shouldn't go negative.

If I press '-' too many time it can become negative right now.

Thanks

**Comment by philseeley** [comment]
Done.

But the handling of alarms does need an update to the app framework, as currently the alarm will only sound if the Anchor Alarm Box is on the visible page. There are also issues with the OS like Android pausing app if it's not visible. I've raises issue #13 for this.
