### ISSUE TITLE
Ability to show string values

### ISSUE THREAD

**Issue by mgrouch** [philseeley/boatinstrument#24]
Like:

Boat name
MMSI
Registration
Insurance ID
SeaTow ID,
etc

Some of this data is in SignalK.

Thanks

**Comment by philseeley** [comment]
I've experimented with subscribing to paths like "mmsi" and "name", but the server never sends updates, even with a subscription policy of "fixed". I'll raise this with the devs to see if this is supported, or I'm doing something wrong.

**Comment by mgrouch** [comment]
I think those need to be requested. 

Here is how I’ve done it in another project 

https://github.com/bareboat-necessities/bbn-m5stack-tough/blob/main/bbn_m5tough_active_boat/net_signalk_http.h
