### ISSUE TITLE
On Pi linux version swap gesture requires very long swipe. and often horizonal swipe is recognized as vertical

### ISSUE THREAD

**Issue by mgrouch** [philseeley/boatinstrument#6]
On Pi linux version swap gesture requires very long swipe. and often horizonal swipe is recognized as vertical

Thanks

**Comment by philseeley** [comment]
@mgrouch I've committed a [fix](https://github.com/philseeley/boatinstrument/commit/aab71395a4d609b5d844fd9097d4045c5c1f537f) for this and bumped the version number.

Let me know if this doesn't resolve it.

**Comment by mgrouch** [comment]
Yes. This works! 

Thanks
